config/routes.rb
EpicLife::Application.routes.draw do
  resources :people do
    # resources :activities
    resources :feats
  end

  resources :activities do
    # resources :feats
  end
end

app/models/feat.rb
class Feat < ActiveRecord::Base
  belongs_to :person
  belongs_to :activity
  
  scope :completed, :conditions => "completed = 't'"


  def complete
      self.completed = true
      self.xp = self.activity.xp
      save
  end

  def uncomplete
      self.completed = false
      save
  end
  
  def date
    activity.start_time.to_date
  end
  
  def activity_type
    activity.activity_type
  end
  
  def calculate_streak
    streak = filter_streak_candidates_based_on_period(get_streak_candidates, activity_type.period)
    streak.length
  end
  
  private
  
  # candidates are: all completed feats by the same person of same activity type
  def get_streak_candidates
    streak_candidates = person.feats.completed
    streak_candidates = streak_candidates.includes(:activity)
    streak_candidates = streak_candidates.where(["activities.activity_type_id = ?",activity_type.id])
  end
  
  # return candidates which are within the streak period of each other, working our way backwards in time
  def filter_streak_candidates_based_on_period(streak_candidates, period)
    streak_candidates = streak_candidates.order("activities.start_time DESC")
    streak = []
    return streak if streak_candidates.blank?

    start_time = streak_candidates.first.date
    streak_candidates.each do |streak_candidate| 
      if ((start_time - period)..(start_time)).include? streak_candidate.date
        streak << streak_candidate
        start_time = streak_candidate.date
      else
        break
      end
    end
    
    streak
  end

end

app/controllers/feats_controller.rb
class FeatsController < ApplicationController
  before_filter :get_user

  # GET /feats
  # GET /feats.xml
  def index
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.today
    beginning_of_day, end_of_day = @date.beginning_of_day, @date.end_of_day
    @feats = @person.feats.all(
      :include => :activity, 
      :conditions => ["activities.start_time > ? and activities.start_time < ?", beginning_of_day, end_of_day])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feats }
    end
  end

  # GET /feats/1
  # GET /feats/1.xml
  def show
    @feat = @person.feats.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feat }
    end
  end

  # GET /feats/new
  # GET /feats/new.xml
  def new
    @feat = @person.feats.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feat }
    end
  end

  # GET /feats/1/edit
  def edit
    @feat = @person.feats.find(params[:id])
  end

  # POST /feats
  # POST /feats.xml
  def create
    @feat = @person.feats.new(params[:feat])

    respond_to do |format|
      if @feat.save
        format.html { redirect_to([@person, @feat], :notice => 'Feat was successfully created.') }
        format.xml  { render :xml => @feat, :status => :created, :location => @feat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feats/1
  # PUT /feats/1.xml
  def update
    @feat = @person.feats.find(params[:id])
    level_old = @person.level

    if params[:feat][:completed] == '1'
        @feat.complete
    else
        @feat.uncomplete
    end
    sign = params[:feat][:completed] == '1' ? '+': '-'
    
    has_leveled = @person.level > level_old

    respond_to do |format|
        format.json { render :json => {
            :xpGained => "#{sign}#{@feat.xp}",
            :xpTotal => @person.xp,
            :next_level_ratio => @person.next_level_ratio,
            :extra_life => @person.level_to_string,
            :has_leveled => has_leveled,
            :completed => @feat.completed,
            :streak => @feat.calculate_streak}}
    
    end

  end

  # DELETE /feats/1
  # DELETE /feats/1.xml
  def destroy
    @feat = @person.feats.find(params[:id])
    @feat.destroy

    respond_to do |format|
      format.html { redirect_to(person_feats_url(@person)) }
      format.xml  { head :ok }
    end
  end

  private
  def get_user
    @person = Person.find(params[:person_id]) unless params[:person_id].blank?
  end
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/views/feats/_form.html.erb
<%= form_for([@person, @feat]) do |f| %>
  <% if @feat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feat.errors.count, "error") %> prohibited this feat from being saved:</h2>

      <ul>
      <% @feat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br />
    <%= f.text_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :xp %><br />
    <%= f.text_field :xp %>
  </div>
  <div class="field">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feats/edit.html.erb
<h1>Editing feat</h1>

<%= render 'form' %>

<%= link_to 'Show', person_feat_path(@feat) %> |
<%= link_to 'Back', person_feats_path(@person) %>

app/views/feats/index.html.erb
<section id="stats" data-person_id="<%= @person.id %>" class="clearfix">
    <h2><%= @person.name %></h2>
    <img class="avatar" src="<%= @person.avatar_url_or_fallback %>" alt="Martins avatar" />
    <div id="xp_meter" data-current_xp="<%= @person.xp %>" data-next_level_ratio="<%= @person.next_level_ratio%>">
        <div>XP: <%= @person.xp %>/<%= @person.xp_for_next %></div>
    </div>
    <p id="ranking">Ranking: <%= @person.ranking %> av <%= Person.count %></p>
    <p id="extra_life">Extraliv: <%= @person.level_to_string %> </p>
</section>
<section id="feats">
    <header>
        <h2><time><%= @date.to_s(:short) %></time></h2>
        <nav class="clearfix">
            <ul>
                <li class="previous"><a href="?date=<%= (@date - 1).to_s(:db) %>">&laquo; <time><%= (@date - 1).to_s(:short) %></time></a></li>
                <li class="next"><a href="?date=<%= (@date + 1).to_s(:db) %>"><time><%= (@date + 1).to_s(:short) %></time> &raquo;</a></li>
            <ul>
        </nav>
    </header>
    <ol>
        <% @feats.each do |feat| %>
            <li style="display:block;">
            <a class="feat<%= " completed" if feat.completed? %>" href="#" data-id="<%= feat.id %>" data-completed="<%= feat.completed %>" ><%= feat.activity.title %></a><span class="streak" ><%= feat.calculate_streak %></span>
            </li>
        <% end %>
    </ol>
    <p id="new"><%= link_to('Lägg till ny', new_person_feat_path(@person)) %></p>
</section>

app/views/feats/new.html.erb
<h1>New feat</h1>

<%= render 'form' %>

<%= link_to 'Back', person_feats_path(@person) %>

app/views/feats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @feat.person_id %>
</p>

<p>
  <b>Activity:</b>
  <%= @feat.activity_id %>
</p>

<p>
  <b>Xp:</b>
  <%= @feat.xp %>
</p>

<p>
  <b>Completed:</b>
  <%= @feat.completed ? "true" : "false" %>
</p>

<%= link_to 'Edit', edit_person_feat_path(@person, @feat) %> |
<%= link_to 'Back', person_feats_path(@person) %>